name: 'Should Deploy Branch'
description: 'Whether to deploy a branch or not'
inputs:
  current_branch:  # id of input
    description: 'The current name of branch e.g. dev, qa, sit, etc'
    required: true
  allow_branches:
    description: 'Branches array to allow'
    required: true
outputs:
  should_deploy: # id of output
    description: 'Whether to deploy or not'
runs:
  using: 'node16'
  main: 'index.js'